nelmio_api_doc:
    documentation:
        info:
            title: Rosatom Backend
            description: Rosatom API
            version: 1.0.0
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
