version: '3'

services:
    db:
        container_name: db
        image: mysql:5.7
        ports:
            - 33061:3306
        restart: always
        volumes:
            - ./docker/data/db:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpwd}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-rosatom}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-userpwd}
        networks:
            - app

    php:
        container_name: php
        build: docker/php/
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - /etc/timezone:/etc/timezone:cached
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpwd}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-rosatom}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-userpwd}
        networks:
            - app

    nginx:
        container_name: nginx
        image: nginx:1.16.0-alpine
        ports:
            - ${DOCKER_NGINX_PORT:-8000}:80
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        networks:
            - app

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app

    node:
        image: node:13.12.0-alpine
        volumes:
            - ./:/var/www/symfony
        working_dir: /var/www/symfony

networks:
    app:
        driver: bridge

volumes:
    data:
        driver: local